"""Regression battery for labeling REAL simulated fields, incl. the single DKS.

`label_history` (which feeds the training dataset) is produced by the JAX
scan-time labeler, so a genuine single dissipative Kerr soliton MUST be labeled
class 6 by the JAX path — not the "chaotic" class 3. This battery pins that on
actual solver output (saved as fixtures in tests/data/), covering:

  * a validated single DKS at n_tau = 512 AND n_tau = 2048  -> class 6
  * a held-CW field                                          -> class 1
  * an MI/Turing field                                       -> class 2
  * a disordered class-3 field                               -> class 3

It requires JAX and NumPy to agree with zero disagreements
(`assert_labelers_consistent`, atol=0), and checks that the sech^2
envelope-correlation metric is DISCRIMINATIVE (high only for the soliton, low
for MI/chaos), so class 6 cannot be reached by simply having a broad spectrum.

Fixtures are regenerated by scratch tooling; see analysis/dks_access.py for the
generators (access_by_seeding for the DKS, cold start for CW, seeding at 2*kappa
for MI, and an overcrowded soliton seed for the class-3 field).
"""

from __future__ import annotations

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest

from analysis.dks_access import load_cavity_params, sech2_envelope_correlation
from simulator.state_labeler import (
    assert_labelers_consistent,
    label_soliton_state,
    make_state_labeler,
    make_threshold_params,
)

DATA = Path(__file__).resolve().parent / "data"
PIN = 0.214

# field fixture -> expected 7-class label
EXPECTED = {
    "dks_512": 6,
    "dks_2048": 6,
    "cw_512": 1,
    "mi_512": 2,
    "chaos_512": 3,
}


@pytest.fixture(scope="module")
def params():
    cav = load_cavity_params()
    # single source of truth: same physical OFF floor the solver uses at this point
    return make_threshold_params(cav.kappa, cav.kappa_c, PIN, 8.0 * cav.kappa)


def _load(name):
    return np.load(DATA / f"{name}.npy")


@pytest.mark.parametrize("name", list(EXPECTED))
def test_jax_label_matches_expected(name, params):
    e = _load(name)
    label = int(make_state_labeler(params)(jnp.array(e, dtype=jnp.complex64)))
    assert label == EXPECTED[name], f"JAX labeled {name} as {label}, expected {EXPECTED[name]}"


@pytest.mark.parametrize("name", list(EXPECTED))
def test_numpy_label_matches_expected(name, params):
    e = _load(name)
    label = label_soliton_state(e, threshold_params=params)
    assert label == EXPECTED[name], f"NumPy labeled {name} as {label}, expected {EXPECTED[name]}"


@pytest.mark.parametrize("name", list(EXPECTED))
def test_labelers_consistent_atol0(name, params):
    # zero JAX/NumPy disagreements across the real-field battery
    assert_labelers_consistent(_load(name), atol=0.0, threshold_params=params)


def test_single_dks_is_class_6_both_resolutions(params):
    """The headline regression: a real single DKS is class 6 in BOTH labelers at
    n_tau=512 and n_tau=2048 (previously the JAX labeler called it chaotic=3)."""
    for name in ("dks_512", "dks_2048"):
        e = _load(name)
        assert int(make_state_labeler(params)(jnp.array(e, dtype=jnp.complex64))) == 6
        assert label_soliton_state(e, threshold_params=params) == 6


def test_envelope_correlation_is_discriminative():
    """sech^2 envelope correlation must score the soliton HIGH and MI/chaos LOW,
    so class 6 is not reachable merely by having a broad spectrum."""
    corr = {n: sech2_envelope_correlation(_load(n))[0] for n in EXPECTED}
    # soliton: high at both resolutions
    assert corr["dks_512"] > 0.9, corr
    assert corr["dks_2048"] > 0.9, corr
    # MI and chaos: low (finite and well below the soliton bar)
    assert np.isfinite(corr["mi_512"]) and corr["mi_512"] < 0.5, corr
    assert np.isfinite(corr["chaos_512"]) and corr["chaos_512"] < 0.5, corr
    # a clear separation margin between the soliton and the worst non-soliton
    worst_non_soliton = max(corr["mi_512"], corr["chaos_512"])
    assert corr["dks_512"] - worst_non_soliton > 0.5, corr
