#!/usr/bin/env python
"""One-page manifest of analysis/results/ + hard-checked cross-artifact assertions.

Run from the repo root::

    python scripts/artifact_manifest.py

The manifest is the audit record for the artifact-consistency pass (task A):
every file under ``analysis/results/`` is listed with the script that GENERATES
it and whether THIS consistency pass touched it (regenerated it, corrected it,
or only verified it).  The ``touched`` column is derived from ``git status`` so
it reflects the real working-tree footprint, not a hand-maintained list -- a
file the pass regenerated byte-for-byte identically shows as ``regen (identical)``
(git sees no change), while a genuine content change shows as ``modified``.

The CHECKED SECTION (task B) is a set of cross-artifact consistency assertions
that HARD-FAIL (nonzero exit) on violation, so the manifest doubles as a
regression gate: the single-DKS existence edge, the stationary/breather bands
and the staircase matched-steps must stay mutually consistent across
``detuning_sweep.npz``, ``dks_existence_map.csv`` / ``dks_breathing_scan.csv``
and ``spectral_metrics.json``.

Nothing here re-runs the solver or regenerates an artifact; it is pure
post-processing of the committed files.
"""

from __future__ import annotations

import csv
import json
import subprocess
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from analysis.spectral_metrics import single_dks_region  # noqa: E402

RESULTS = REPO_ROOT / "analysis" / "results"

# --- generating-script map (the script that WRITES each artifact) ------------
# role annotates what the pass did to it: "regen" = rewritten by
# regenerate_dks_artifacts.py; "metrics" = (re)written by
# compute_spectral_metrics.py; "sweep" = written by run_detuning_sweep.py;
# "robustness" = written by run_detuning_sweep.py --robustness; other analyses
# own the remaining files and are outside this pass's scope.
GEN = {
    "detuning_sweep.npz": ("analysis/run_detuning_sweep.py", "sweep"),
    "soliton_steps.png": ("analysis/run_detuning_sweep.py", "sweep"),
    "soliton_steps.pdf": ("analysis/run_detuning_sweep.py", "sweep"),
    "dks_single_soliton_spectrum.npz": ("scripts/regenerate_dks_artifacts.py", "regen"),
    "dks_single_soliton_spectrum.png": ("scripts/regenerate_dks_artifacts.py", "regen"),
    "dks_single_soliton_summary.png": ("scripts/regenerate_dks_artifacts.py", "regen"),
    "dks_breathing_scan.csv": ("scripts/regenerate_dks_artifacts.py", "regen"),
    "dks_breathing_scan.png": ("scripts/regenerate_dks_artifacts.py", "regen"),
    "dks_existence_map.csv": ("scripts/regenerate_dks_artifacts.py (breathing-column merge; "
                              "base by analysis/dks_access.py)", "regen"),
    "dks_existence_map.png": ("analysis/dks_access.py (plot_existence_map)", "other"),
    "dks_spectrum_3db_span.png": ("analysis/compute_spectral_metrics.py", "metrics"),
    "dks_spectrum_3db_span.pdf": ("analysis/compute_spectral_metrics.py", "metrics"),
    "spectral_metrics.json": ("analysis/compute_spectral_metrics.py (three_db_span, "
                              "conversion_efficiency) + analysis/run_detuning_sweep.py "
                              "(soliton_step, staircase_robustness)", "metrics+sweep"),
    "dks_artifact_provenance.json": ("scripts/regenerate_dks_artifacts.py (+ "
                                     "run_detuning_sweep.py --robustness: "
                                     "staircase_robustness key)", "regen+robustness"),
    "dks_access_report.md": ("analysis/dks_access.py (write_report)", "other"),
    "adiabatic_sweeps.png": ("analysis/adiabatic_sweeps.py", "other"),
    "adiabatic_sweeps_report.md": ("analysis/adiabatic_sweeps.py", "other"),
    "control_held_cw.csv": ("analysis/adiabatic_sweeps.py", "other"),
    "forward_sweep.csv": ("analysis/adiabatic_sweeps.py", "other"),
    "reverse_sweep.csv": ("analysis/adiabatic_sweeps.py", "other"),
    "staircase_forensics.md": ("analysis/staircase_forensics.py", "other"),
    "robustness/variant_1.npz": ("analysis/run_detuning_sweep.py --robustness", "robustness"),
    "robustness/variant_2.npz": ("analysis/run_detuning_sweep.py --robustness", "robustness"),
    "robustness/variant_3.npz": ("analysis/run_detuning_sweep.py --robustness", "robustness"),
}

# What THIS pass did to each artifact (its intended action), independent of
# whether the bytes changed -- a deterministic regeneration can reproduce a file
# exactly, which is itself the consistency result worth recording.
PASS_ACTION = {
    "dks_single_soliton_spectrum.npz": "regenerated (10k snapshot)",
    "dks_single_soliton_spectrum.png": "regenerated (10k snapshot)",
    "dks_single_soliton_summary.png": "regenerated (10k snapshot)",
    "dks_breathing_scan.csv": "regenerated (breathing scan)",
    "dks_breathing_scan.png": "regenerated (breathing scan)",
    "dks_existence_map.csv": "regenerated (breathing-column merge)",
    "dks_artifact_provenance.json": "regenerated + robustness key appended",
    "dks_spectrum_3db_span.png": "regenerated (3 dB span overlay)",
    "dks_spectrum_3db_span.pdf": "regenerated (3 dB span overlay)",
    "spectral_metrics.json": "three_db_span+conversion_efficiency recomputed; "
                             "staircase_robustness added",
    "detuning_sweep.npz": "VERIFIED ONLY (not regenerated)",
    "soliton_steps.png": "VERIFIED ONLY (not regenerated)",
    "soliton_steps.pdf": "VERIFIED ONLY (not regenerated)",
    "robustness/variant_1.npz": "written by robustness harness",
    "robustness/variant_2.npz": "written by robustness harness",
    "robustness/variant_3.npz": "written by robustness harness",
}


def _git_status_map() -> dict:
    """relpath (under analysis/results/) -> git status code (' M', '??', ...)."""
    out = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "status", "--porcelain",
         "analysis/results"],
        capture_output=True, text=True).stdout
    status = {}
    for line in out.splitlines():
        if not line.strip():
            continue
        code, path = line[:2], line[3:].strip()
        rel = str(Path(path).relative_to("analysis/results"))
        status[rel] = code
    return status


def print_manifest() -> None:
    status = _git_status_map()
    files = sorted(p.relative_to(RESULTS).as_posix()
                   for p in RESULTS.rglob("*") if p.is_file())
    print("=" * 100)
    print("ARTIFACT MANIFEST  --  analysis/results/  (artifact-consistency pass)")
    print("=" * 100)
    print(f"{'file':<40} {'generating script':<46} {'this pass'}")
    print("-" * 100)
    for rel in files:
        gen = GEN.get(rel, ("(unmapped)", "other"))[0]
        code = status.get(rel, "")
        action = PASS_ACTION.get(rel)
        if code == "??":
            touched = "NEW (this pass)"
        elif code.strip():
            touched = f"modified [{code.strip()}]"
        elif action and "VERIFIED ONLY" in action:
            touched = "verified only"
        elif action:
            touched = "regen (identical)"    # rewritten, byte-identical -> no git change
        else:
            touched = "untouched"
        note = f"  ({action})" if action else ""
        gen_disp = (gen[:44] + "..") if len(gen) > 46 else gen
        print(f"{rel:<40} {gen_disp:<46} {touched}{note}")
    print("-" * 100)
    print("Legend: 'regen (identical)' = deterministically regenerated this pass and")
    print("        reproduced byte-for-byte (the consistency result); 'modified' = real")
    print("        content change; 'verified only' = read + checked, never rewritten.")
    print()


# ---------------------------------------------------------------------------
# CHECKED SECTION (task B): hard cross-artifact consistency assertions
# ---------------------------------------------------------------------------
def _load_sweep():
    d = np.load(RESULTS / "detuning_sweep.npz", allow_pickle=False)
    order = np.argsort(d["dw_over_kappa"])
    return {
        "dw": d["dw_over_kappa"][order],
        "is_single": d["is_single"][order].astype(bool),
        "is_breather": d["is_breather"][order].astype(bool),
        "is_stationary": d["is_stationary"][order].astype(bool),
        "soliton_count": d["soliton_count"][order].astype(int),
        "n_solitons_seeded": int(d["n_solitons_seeded"]),
    }


def _contiguous_true_band(x, flag):
    """[lo, hi] of the single longest contiguous True run of ``flag`` over ``x``."""
    lo, hi, _ = single_dks_region(x, flag)
    return (lo, hi)


def checked_section() -> list:
    """Run task-B assertions; return the list of (name, ok, detail) results."""
    sweep = _load_sweep()
    dw = sweep["dw"]
    grid = float(np.median(np.diff(dw)))
    checks = []

    # ---- B1: single-DKS existence lower edge (sweep vs existence map) --------
    _, _, sweep_edge = single_dks_region(dw, sweep["is_single"])
    rows = list(csv.DictReader(open(RESULTS / "dks_existence_map.csv")))
    mdw = np.array([float(r["dw_over_kappa"]) for r in rows])
    mis = np.array([int(r["is_single"]) for r in rows], dtype=bool)
    _, _, map_edge = single_dks_region(mdw, mis)
    # one existence-map grid step at the edge (its native resolution there)
    map_grid = float(np.median(np.diff(np.sort(mdw)[np.sort(mdw) <= 7.0]))) \
        if (np.sort(mdw) <= 7.0).sum() > 1 else 0.5
    # breathing scan lower bound (all-single over its range -> only an UPPER
    # bound on the edge; it must sit above the measured edge)
    brows = list(csv.DictReader(open(RESULTS / "dks_breathing_scan.csv")))
    bscan_lo = min(float(r["dw_over_kappa"]) for r in brows)
    diff = abs(sweep_edge - map_edge)
    ok1 = (diff <= map_grid + 1e-9) and (bscan_lo >= sweep_edge - 1e-9)
    checks.append((
        "B1 single-DKS lower edge agreement",
        ok1,
        f"sweep edge {sweep_edge:.4f}k vs existence-map edge {map_edge:.4f}k "
        f"(|Δ|={diff:.4f}k <= one map grid step {map_grid:.3f}k); breathing-scan "
        f"lower bound {bscan_lo:.2f}k sits above the edge (consistent)."))

    # ---- B2: stationary/breather bands + the 10k hold ------------------------
    hi95 = dw >= 9.5
    all_stat_hi = bool(sweep["is_stationary"][hi95].all())
    band = (dw >= 6.5) & (dw <= 9.0)
    breather_in_band = bool(sweep["is_breather"][band].any())
    i10 = int(np.argmin(np.abs(dw - 10.0)))
    hold10_stat = bool(sweep["is_stationary"][i10])
    hold10_count = int(sweep["soliton_count"][i10])
    hold10_ok = hold10_stat and (hold10_count == sweep["n_solitons_seeded"])
    ok2 = all_stat_hi and breather_in_band and hold10_ok
    checks.append((
        "B2 stationary/breather bands + 10k hold",
        ok2,
        f"every hold dw>=9.5k is_stationary={all_stat_hi} "
        f"(n={int(hi95.sum())}); is_breather present in 6.5-9.0k="
        f"{breather_in_band}; 10k hold (dw={dw[i10]:.3f}) is_stationary="
        f"{hold10_stat}, soliton_count={hold10_count}==seeded N "
        f"{sweep['n_solitons_seeded']} (the sweep never visits N=1 at 10k -- "
        f"that is the spectrum path's state, not the sweep's)."))

    # ---- B3: staircase matched steps lie inside the breather sub-band --------
    with open(RESULTS / "spectral_metrics.json") as f:
        metrics = json.load(f)
    stair = metrics["soliton_step"]["staircase"]
    matched = [float(m["dw_mid"]) for m in stair["matched_steps"]]
    b_lo, b_hi = _contiguous_true_band(dw, sweep["is_breather"])
    # edge midpoints are half-grid-offset from hold detunings, so an edge at the
    # band boundary sits exactly grid/2 outside the nearest breather HOLD; the
    # half-grid guard is the exact discretization correction, not a fudge (the
    # 1->0 edge connects the last breather hold to the first stationary hold).
    ext_lo, ext_hi = b_lo - grid / 2, b_hi + grid / 2
    inside = [ext_lo - 1e-9 <= m <= ext_hi + 1e-9 for m in matched]
    ok3 = bool(matched) and all(inside)
    checks.append((
        "B3 matched staircase steps in breather sub-band",
        ok3,
        f"matched_steps={[round(m,4) for m in matched]} (non-empty={bool(matched)}); "
        f"breather sub-band [{b_lo:.3f}, {b_hi:.3f}]k, edge-midpoint-guarded to "
        f"[{ext_lo:.4f}, {ext_hi:.4f}]k; all inside={all(inside)} "
        f"(the 1->0 edge sits at the guarded lower boundary: its high side is the "
        f"last breather hold)."))

    return checks


def main() -> None:
    print_manifest()
    print("=" * 100)
    print("CHECKED SECTION (task B) -- cross-artifact consistency assertions "
          "(hard-fail)")
    print("=" * 100)
    checks = checked_section()
    failed = []
    for name, ok, detail in checks:
        print(f"[{'PASS' if ok else 'FAIL'}] {name}")
        print(f"       {detail}")
        if not ok:
            failed.append(name)
    print("-" * 100)
    if failed:
        print(f"MANIFEST CHECK FAILED: {len(failed)} assertion(s) violated: "
              + ", ".join(failed))
        sys.exit(1)
    print(f"ALL {len(checks)} CROSS-ARTIFACT ASSERTIONS PASS.")


if __name__ == "__main__":
    main()
