#!/usr/bin/env python
"""Compute the cycle-averaged spectral metrics of the validated single DKS.

This is the thin CLI entry point for the metrics in
:mod:`analysis.spectral_metrics`.  It loads the committed CYCLE-AVERAGED
single-soliton spectrum (``analysis/results/dks_single_soliton_spectrum.npz``,
regenerated by ``scripts/regenerate_dks_artifacts.py``), computes the metric(s),
updates ``analysis/results/spectral_metrics.json`` idempotently (each metric
under its own key, with units, the metric definition, and provenance), and
regenerates the annotated overlay plot.

Feature 1 adds the ``three_db_span`` block and the
``dks_spectrum_3db_span.{png,pdf}`` overlay.  The original validated
``dks_single_soliton_spectrum.png`` is never touched.

Usage
-----
    python analysis/compute_spectral_metrics.py            # committed npz
    python analysis/compute_spectral_metrics.py --spectrum path/to/other.npz

The mode spacing (FSR) is pulled from the config / measured dispersion via
``analysis.dks_access`` -- never hardcoded.  The averaging that makes the input
spectrum a reproducible observable happens upstream (per-round-trip accumulation
of ``|a_mu|**2`` in LINEAR power over >= 2 breathing periods); this script only
consumes that averaged spectrum.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # repo root

from analysis.dks_access import (  # noqa: E402  (needs the sys.path insert)
    CONFIG_PATH,
    RESULTS_DIR,
    attach_dispersion,
    load_cavity_params,
)
from analysis.spectral_metrics import (  # noqa: E402
    comb_line_powers,
    plot_spectrum_with_span,
    sech2_core_fwhm,
    three_db_span,
)

SPECTRUM_NPZ = "dks_single_soliton_spectrum.npz"
METRICS_JSON = "spectral_metrics.json"
SPAN_PLOT_PNG = "dks_spectrum_3db_span.png"


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _load_spectrum(npz_path: Path) -> dict:
    """Load a cycle-averaged spectrum npz into ``mu`` and linear power ``P_mu``.

    Uses ``power_norm`` (linear, pump normalised to 1) when present, else
    delinearises ``power_db``.  Carries through the averaging/breather
    metadata for provenance.
    """
    d = np.load(npz_path)
    mu = np.asarray(d["mu"]).astype(np.int64)
    if "power_norm" in d.files:
        P = np.asarray(d["power_norm"], dtype=np.float64)
    else:
        P = 10.0 ** (np.asarray(d["power_db"], dtype=np.float64) / 10.0)
    meta = {
        "n_rt_averaged": int(d["n_rt_averaged"]) if "n_rt_averaged" in d.files
        else None,
        "breathing_period_rt": float(d["breathing_period_rt"])
        if "breathing_period_rt" in d.files else None,
        "breathing_relstd": float(d["breathing_relstd"])
        if "breathing_relstd" in d.files else None,
    }
    return {"mu": mu, "P_mu": P, "meta": meta}


def _update_json(json_path: Path, key: str, block: dict) -> None:
    """Idempotently write ``block`` under ``key`` in the metrics JSON."""
    data = {}
    if json_path.exists():
        with open(json_path) as f:
            data = json.load(f)
    data[key] = block
    with open(json_path, "w") as f:
        json.dump(data, f, indent=2, default=float)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spectrum", type=Path,
                    default=RESULTS_DIR / SPECTRUM_NPZ,
                    help="cycle-averaged spectrum npz (default: committed run)")
    ap.add_argument("--delta-omega-over-kappa", type=float, default=8.0,
                    help="operating detuning [kappa] (annotation only)")
    ap.add_argument("--floor-db", type=float, default=60.0)
    ap.add_argument("--interp-factor", type=int, default=10)
    ap.add_argument("--level-db", type=float, default=3.0)
    ap.add_argument("--smooth-modes", default="auto",
                    help="median window: 'auto' (data-derived) or an odd int")
    args = ap.parse_args()

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    spec = _load_spectrum(args.spectrum)
    mu, P = comb_line_powers(spec["P_mu"], spec["mu"])
    n_tau = int(mu.size)

    # FSR from the measured dispersion (consistent with the npz frequency grid),
    # falling back to the config FSR -- never hardcoded.
    cav = attach_dispersion(load_cavity_params(), n_tau)
    fsr_hz = float(cav.fsr_measured_hz if cav.fsr_measured_hz is not None
                   else cav.fsr_hz)

    metadata = {
        "fsr_hz": fsr_hz,
        "pump_mu": 0,
        "delta_omega_over_kappa": args.delta_omega_over_kappa,
        "n_rt_averaged": spec["meta"]["n_rt_averaged"],
    }

    smooth = args.smooth_modes
    if smooth != "auto":
        smooth = int(smooth)

    span = three_db_span(mu, P, metadata, smooth_modes=smooth,
                         floor_db=args.floor_db, interp_factor=args.interp_factor,
                         level_db=args.level_db)
    cross = sech2_core_fwhm(mu, P, fsr_hz=fsr_hz, level_db=args.level_db)

    provenance = {
        "input_file": str(args.spectrum.relative_to(Path(__file__).resolve().parents[1]))
        if args.spectrum.is_absolute() and str(args.spectrum).startswith(
            str(Path(__file__).resolve().parents[1])) else str(args.spectrum),
        "input_sha256": _sha256(args.spectrum),
        "config_file": str(CONFIG_PATH.name),
        "config_sha256": _sha256(CONFIG_PATH),
        "run_id": {
            "n_rt_averaged": spec["meta"]["n_rt_averaged"],
            "breathing_period_rt": spec["meta"]["breathing_period_rt"],
            "breathing_relstd": spec["meta"]["breathing_relstd"],
        },
        "fsr_hz": fsr_hz,
        "fsr_source": ("measured dispersion (attach_dispersion) "
                       if cav.fsr_measured_hz is not None else "config"),
        "n_tau": n_tau,
        "generated_utc": _dt.datetime.now(_dt.timezone.utc).isoformat(),
        "module": "analysis/spectral_metrics.py",
        "script": "analysis/compute_spectral_metrics.py",
    }

    block = dict(span)
    block["sech2_core_fwhm_crosscheck"] = cross
    block["provenance"] = provenance

    json_path = RESULTS_DIR / METRICS_JSON
    _update_json(json_path, "three_db_span", block)

    title_extra = ""
    m = spec["meta"]
    if m["breathing_period_rt"] and np.isfinite(m["breathing_period_rt"]):
        title_extra = (f"breather T~{m['breathing_period_rt']:.0f} RT, "
                       f"dU/U={100.0 * m['breathing_relstd']:.1f}%")
    plot_path = plot_spectrum_with_span(
        mu, P, span, RESULTS_DIR / SPAN_PLOT_PNG, metadata=metadata,
        title_extra=title_extra)

    print(f"[metrics] input: {args.spectrum} (n_tau={n_tau})")
    print(f"[metrics] FSR = {fsr_hz:.6e} Hz ({provenance['fsr_source'].strip()})")
    if np.isfinite(span["span_modes"]):
        print(f"[metrics] 3 dB span = {span['span_modes']:.1f} modes "
              f"= {span['span_ghz']:.1f} GHz ({span['span_thz']:.3f} THz); "
              f"band mu in [{span['left_crossing_mu']:.1f}, "
              f"{span['right_crossing_mu']:.1f}], median window "
              f"{span['params']['smooth_modes_used']}")
    else:
        print(f"[metrics] 3 dB span = NaN ({'; '.join(span['warnings'])})")
    print(f"[metrics] sech^2 core cross-check FWHM = "
          f"{cross.get('fwhm_modes', float('nan')):.1f} modes "
          f"({cross.get('fwhm_thz', float('nan')):.3f} THz, "
          f"fit RMS {cross.get('fit_rms_db', float('nan')):.2f} dB)")
    for w in span["warnings"]:
        print(f"[metrics] WARNING: {w}")
    print(f"[metrics] JSON  -> {json_path}")
    print(f"[metrics] plot  -> {plot_path} (+ .pdf)")


if __name__ == "__main__":
    main()
